example/user/__init__.py
from flask import Blueprint

# Создание Blueprint для модуля user
user_blueprint = Blueprint('user', __name__, template_folder='templates')

from . import routes  # Импортируем routes для регистрации маршрутов

example/user/routes.py
from flask import render_template, request, redirect, url_for, flash
from . import user_blueprint
from oris.timeweb.utils.database import get_db_connection

"""
    Flask Blueprint  - это способ разделения приложения на более мелкие, модульные компоненты, что помогает улучшить 
    читаемость кода, структурированность проекта и его масштабируемость.
    Основная идея заключается в том, чтобы вынести определённый функционал, маршруты и связанные с ними элементы в отдельный модуль, 
    а затем подключить их к основному приложению.
    
    Основные этапы организации приложения с Blueprint
    Создание модулей приложения:
    Например, модули для пользователей, постов, тегов, авторизации и регистрации.
    
    Создание структуры проекта:
    Каждый модуль будет представлять собой отдельную директорию с файлами для маршрутов, моделей, шаблонов и других ресурсов.
    
    Настройка Blueprint для каждого модуля:
    Каждый модуль будет использовать Blueprint для регистрации своих маршрутов.
    Реализация маршрутов каждого модуля.
    Регистрация Blueprints в основном приложении.
    
    Преимущества использования Flask Blueprint
    Разделение кода на независимые модули, которые проще поддерживать и тестировать.
    
    Возможность использования одного и того же Blueprint в нескольких приложениях.
    
    Компоненты, относящиеся к одной сущности (маршруты, формы, шаблоны), хранятся в одном месте.
"""


@user_blueprint.route("/user")
def get_users():
    conn = get_db_connection()
    users = conn.execute('SELECT * FROM passwords').fetchall()
    conn.close()
    return render_template('users.html', users=users)


# Страница создания нового пользователя
@user_blueprint.route('/user/create_user', methods=('GET', 'POST'))
def create_user():
    if request.method == 'POST':
        login = request.form.get('login')
        password = request.form.get('password')

        conn = get_db_connection()
        conn.execute('INSERT INTO passwords (login, password) VALUES (?, ?)', (login, password))
        conn.execute('INSERT INTO user_profile (login) VALUES (?)', (login,))
        conn.commit()
        conn.close()

        return redirect(url_for('user.get_users'))

    return render_template('create_user.html')


# Страница редактирования пользователя
@user_blueprint.route('/user/<string:login>/edit_user', methods=('GET', 'POST'))
def edit_user(login):
    conn = get_db_connection()
    user = conn.execute('SELECT * FROM passwords WHERE login = ?', (login,)).fetchone()

    if request.method == 'POST':
        new_login = request.form.get('login')
        new_password = request.form.get('password')

        conn.execute('UPDATE passwords SET login = ?, password = ? WHERE login = ?',
                     (new_login, new_password, login))
        conn.commit()
        conn.close()
        return redirect(url_for('user.get_users'))

    conn.close()
    return render_template('edit_user.html', user=user)

# Удаление пользователя
@user_blueprint.route('/user/<string:login>/delete_user', methods=('POST',))
def delete_user(login):
    conn = get_db_connection()
    conn.execute('DELETE FROM passwords WHERE login = ?', (login,))
    conn.commit()
    conn.close()
    flash('Пользователь удален')
    return redirect(url_for('user.get_users'))

example/user/templates/create_user.html
{% extends 'base.html' %}

{% block content %}
    <h1>Добавить нового пользователя</h1>
    <form method="POST">
        <div class="mb-3">
            <label for="login" class="form-label">Логин</label>
            <input class="form-control" type="text" id="login" name="login" required>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Пароль</label>
            <input type="password" class="form-control" id="password" name="password" required>
        </div>
        <button type="submit" class="btn btn-success">Сохранить</button>
        <a href="{{ url_for('user.get_users') }}" class="btn btn-secondary">Назад</a>
    </form>
{% endblock %}

example/user/templates/edit_user.html
{% extends 'base.html' %}

{% block content %}
    <h1>Редактировать пользователя</h1>
    <form method="POST">
        <div class="mb-3">
            <label for="login" class="form-label">Логин</label>
            <input class="form-control" type="text" id="login" name="login" value="{{ user['login'] }}" required>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Пароль</label>
            <input class="form-control" type="text" id="password" name="password" value="{{ user['password'] }}" required>
        </div>
        <button type="submit" class="btn btn-success">Сохранить</button>
        <a href="{{ url_for('index') }}" class="btn btn-secondary">Назад</a>
    </form>
{% endblock %}

example/user/templates/users.html
{% extends "base.html" %}

{% block title %}Главная страница сайта{% endblock %}

{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
<div class="container mt-4">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-warning">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
</div>
<a class="btn btn-primary mb-3" href="{{ url_for('user.create_user') }}">Добавить пользователя</a>
<h1>ПОЛЬЗОВАТЕЛИ</h1>
    {% for user in users %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ user['login'] }}</h5>
                <p class="card-text">{{ user['password'] }}</p>
                <a class="btn btn-secondary" href="{{ url_for('user.edit_user', login=user['login']) }}">Редактировать</a>
                <form action="{{ url_for('user.delete_user', login=user['login']) }}" method="POST" class="d-inline">
                    <button class="btn btn-danger" type="submit">Удалить</button>
                </form>
            </div>
        </div>
    {% endfor %}
{% endblock %}